### ISSUE TITLE
Monkey Patch pada Asset

### ISSUE THREAD

**Issue by ejabu** [open-synergy/opnsynid-account-financial-tools#44]
https://github.com/open-synergy/opnsynid-account-financial-tools/blob/8b852ac07d7b1e36520fdb4d7f2f6b3557acbb7a/account_asset_management_extend/models/account_asset_asset_monkeypatch.py#L634

Mas mau tanya,

apakah Monkey Patch ini akan ada efek untuk environment satu Odoo satu Custom Addons path dan multi-database ?

misal, saya punya 2 database yg running dengan satu Odoo Python Server.

db_pertama di-install modul account_asset_management_extend.

sedangkan db_kedua tidak di-install modul diatas

saya menemukan fungsionalitas modul aset pada db_kedua akan sama pada db_pertama jika kedua db diakses bersamaan.

apakah hal ini bisa dihindari ?

atau mau tidak mau solusinya adalah running db_kedua dengan Odoo Python server yg lain ?

terima kasih Mas

**Comment by andhit-r** [comment]
@ejabu monkey patch akan mengakibatkan modul harus diinstall di semua db. Ini tidak bisa dihindari jika menggunakan strategi monkey patch. Solusi running dengan odoo server yg lain tergantung dr ketersediaan rsource. Namun demikian saya tidak menyarankan hal tsb.

Monkey patch dibuat harusnya dengan tidak merusak fungsionalitas di modul lain.

**Comment by ejabu** [comment]
iya Mas Andhit, kalau case di project saya, itu fungsionalitas diskon di Sale Order - Customer Invoice, dan Purchase Order - Vendor Bill.

kebanyakan discount hanya persentase saja, sedangkan proses bisnis di Indoenesia macem2.

Mas Andhit ada rekomendasi lain untuk workaround discoount percentage dan nominal pada satu line ?

btw thanks Mas udah sharing

**Comment by andhit-r** [comment]
Coba cek ini. Secara fungsional keren menurut saya. Coba ditiru https://www.odoo.com/apps/modules/12.0/promotion_ept/

**Comment by ejabu** [comment]
mesti bayar tapi Mas hehe

**Comment by ejabu** [comment]
mungkin field discountnya tidak ada pada Sales Order Line dan Invoice line ya ?

**Comment by andhit-r** [comment]
Lihat discreenshotnya saja. Lumayan informatif kok
